sonar.projectKey=MORTAKI0_Ega-House-Platform
sonar.organization=mortaki0
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/coverage/**,**/convex/_generated/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info